jenkins_integration: cleaning up VERSION argument by making it a client-side post-commit hook

diff --git a/cookbooks/jenkins_integration/templates/default/new_developments.sh.erb b/cookbooks/jenkins_integration/templates/default/new_developments.sh.erb
--- a/cookbooks/jenkins_integration/templates/default/new_developments.sh.erb
+++ b/cookbooks/jenkins_integration/templates/default/new_developments.sh.erb
@@ -14,9 +14,31 @@ for name in $PANTRIES; do
   cd $WORKSPACE/$name
   pwd
   if ! git diff --quiet master staging; then
-    echo "Changes found"
-    EXIT_CODE=0;
   fi
+
+  echo "find all cookbook differences between master and staging:"
+  changes=`git diff --name-only staging -- cookbooks/*/ | cut -d/ -f2 | sort | uniq`
+  if [ "x$changes" = "x" ]; then
+    echo "No cookbook changes between master and staging"
+    continue
+  fi
+
+  echo "Changes found"
+  echo $changes
+  if [ $EXIT_CODE == "1" ]; then EXIT_CODE=0; fi
+
+  echo "ensure each change includes a version bump in master:"
+  git checkout master
+  git pull
+  for cookbook in $changes; do
+    if ! git diff --quiet staging -- cookbooks/$cookbook/VERSION; then
+      "ERROR: changes found but no version bump in $cookbook"
+      EXIT_CODE=2
+    fi
+  done
+  echo
+
 done
-if [ ! $EXIT_CODE ]; then echo "No changes found for testing"; fi
+
+if [ $EXIT_CODE == "1" ]; then echo "ERROR: No changes found for testing"; fi
 exit $EXIT_CODE
