jenkins_integration: making ensure_bundle to make sure everything has the right gems

diff --git a/cookbooks/jenkins_integration/templates/default/shared.inc.erb b/cookbooks/jenkins_integration/templates/default/shared.inc.erb
--- a/cookbooks/jenkins_integration/templates/default/shared.inc.erb
+++ b/cookbooks/jenkins_integration/templates/default/shared.inc.erb
@@ -48,6 +48,17 @@ export CHEF_USER=<%= node[:jenkins_integration][:ironfan_ci][:chef_user] %>
 function knife {
   bundle exec knife "$@"
 }
+function berkshelf {
+  bundle exec berks install "$@"; echo
+}
+function ensure_bundle {
+  if ! bundle check; then
+    echo "Installing bundle:"
+    PARAMS="--path $WORKSPACE/vendor --no-color --without=development,support"
+    # Only install from source if cache fails
+    bundle install $PARAMS --local || bundle install $PARAMS
+  fi
+}
 
 # Use the local copies of repos for Berkshelf operations
 export USE_LOCAL=true
